repository_type: pipeline
nf_core_version: 3.2.1
lint:
  nextflow_config:
    - manifest.name
    - manifest.version
    - manifest.homePage
    - params.custom_config_base
  actions_awsfulltest: False
  local_component_structure: False
