repository_type: pipeline
nf_core_version: 3.2.1
lint:
  nextflow_config:
    - manifest.name
    - manifest.version
    - manifest.homePage
    - custom_config
  actions_awsfulltest: false
  actions_ci: false
  local_component_structure: false
