FROM continuumio/miniconda3:4.5.4
LABEL authors="Yanhai Gong" \
      description="Docker image containing all requirements for gongyh/nf-core-scgs pipeline"

# Install procps so that Nextflow can poll CPU usage, set locale en_US.UTF-8 used by Picard
RUN apt-get update && apt-get install --no-install-recommends -y procps libpng16-16 cmake gcc g++ hmmer2 locales && \
  apt-get autoremove --purge && apt-get clean -y && apt-get autoremove && rm -rf /var/lib/apt/lists/* && \
  sed -i 's/^# *\(en_US.UTF-8\)/\1/' /etc/locale.gen && locale-gen

# Install resfinder and pointFinder
RUN cd /opt && git clone https://git@bitbucket.org/genomicepidemiology/resfinder.git
RUN cd /opt && git clone https://bitbucket.org/genomicepidemiology/pointfinder.git

# Install conda environments
COPY scgs_py36.txt /
RUN conda install -y python=3.6 conda=4.6.12 nomkl && conda clean -y -a && rm -rf /opt/conda/pkgs/*
RUN conda create --name scgs_py36 --file /scgs_py36.txt && conda clean -y -a && rm -rf /opt/conda/pkgs/*

# Set default conda env to scgs_py36
RUN echo 'conda activate scgs_py36' >> ~/.bashrc

ENV PATH /opt/conda/envs/scgs_py36/bin:$PATH

# Install Bioconductor packages
RUN R -e "install.packages('BiocManager', repos='https://cloud.r-project.org'); BiocManager::install('GenomeInfoDbData'); BiocManager::install('AneuFinder')"

# Download silva and busco for Quast 5.x, update taxa db for krona
RUN quast-download-silva && ktUpdateTaxonomy.sh #&& quast-download-busco

# Download GATK3 and setting
#RUN wget "https://software.broadinstitute.org/gatk/download/auth?package=GATK-archive&version=3.8-0-ge9d806836" -O GenomeAnalysisTK-3.8.tar.bz2 && \
#    tar xjvf GenomeAnalysisTK-3.8.tar.bz2 && gatk3-register GenomeAnalysisTK-3.8-0-ge9d806836/GenomeAnalysisTK.jar && rm -rf ./GenomeAnalysisTK-3.8*
#COPY GenomeAnalysisTK.jar /
#RUN gatk3-register /GenomeAnalysisTK.jar && rm -rf /GenomeAnalysisTK.jar

# Install conda environment py27
COPY scgs_py27.txt /
RUN conda create --name scgs_py27 --file /scgs_py27.txt nomkl && conda clean -y -a && rm -rf /opt/conda/envs/scgs_py36/pkgs/*

# Install ACDC
RUN git clone https://github.com/mlux86/acdc.git /tmp/acdc && cd /tmp/acdc && mkdir build && cd build && cmake .. -DBOOST_ROOT=/opt/conda/envs/scgs_py36/ && \
    make -j $(nproc) && make install && rm -rf /tmp/acdc && mkdir /acdc

# Install rnammer
RUN mkdir /tmp/rnammer
ADD rnammer-1.2.src.tar.Z /tmp/rnammer
ADD rnammer.patch /tmp/rnammer
RUN cd /tmp/rnammer && tar xf rnammer-1.2.src.tar.Z && rm rnammer-1.2.src.tar.Z && patch < rnammer.patch && mkdir /usr/local/share/rnammer && \
    cp -r * /usr/local/share/rnammer && ln -s /usr/local/share/rnammer/rnammer /usr/local/bin/rnammer && rm -rf /tmp/rnammer

# Build database for blobtools
RUN [ "/bin/bash", "-c", "source activate scgs_py27 && blobtools-build_nodesdb && source deactivate" ]

# Install Funannotate
#RUN [ "/bin/bash", "-c", "source activate scgs_py27 && conda install -c bioconda -c conda-forge trnascan-se=1.3.1 funannotate=1.7.2 && conda clean -y -a && rm -rf /opt/conda/pkgs/* && source deactivate" ]

# Install kofamscan
RUN cd /opt && wget https://github.com/takaram/kofam_scan/archive/v1.1.0.tar.gz -O kofamscan-1.1.0.tar.gz && \
    tar --no-same-owner -xzvf kofamscan-1.1.0.tar.gz && rm -rf kofamscan-1.1.0.tar.gz

# Install R packages
RUN R -e "install.packages(c('magicaxis','ape','gridExtra','hyperSpec'), repos='https://cloud.r-project.org')"

# Install mccortex
RUN cd /opt && git clone --recursive https://github.com/mcveanlab/mccortex && cd mccortex && apt update && \
    apt install -y autoconf automake zlib1g-dev libncurses5-dev libncursesw5-dev fastx-toolkit && \
    make all && apt-get autoremove --purge && apt-get clean && apt-get autoremove

# Install fastp
RUN cd /usr/local/bin && wget http://opengene.org/fastp/fastp && chmod a+x ./fastp

# Keep a copy of current pipeline to container
COPY . /opt/nf-core-scgs/

# Add default container command
CMD ["/opt/conda/bin/nextflow", "run", "/opt/nf-core-scgs/main.nf", "--help"]

