%%metro style: nfcore
%%metro animate: true
%%metro compact_offsets: true
%%metro legend: bl
%%metro line: reference | With reference genome | #F58518
%%metro line: assembly | Without reference genome | #54A24B
%%metro legend_combo: reference, assembly | Read quality control
%%metro marker_legend: circle, solid | Database-free process
%%metro marker_legend: square, solid | Database-dependent process
%%metro marker: kraken | square, solid
%%metro marker: checkm | square, solid
%%metro marker: genomad | square, solid
%%metro marker: blobtools | square, solid
%%metro marker: acdc | square, solid
%%metro marker: eggnog | square, solid
%%metro marker: kofamscan | square, solid
%%metro marker: gtdbtk | square, solid
%%metro grid: read_preparation | 0,0
%%metro grid: assembly_stage | 1,1
%%metro grid: reference_analyses | 1,0

graph LR

    subgraph read_preparation [Quality control]
        %%metro direction: TB
        raw_reads([Raw reads])
        fastqc([FastQC])
        trimgalore([TrimGalore])
        bbmap_align([Host removal])
        kraken([Kraken])
        clean_reads([Clean reads])

        raw_reads -->|reference,assembly| fastqc
        trimgalore -->|reference,assembly| bbmap_align
        raw_reads -->|reference,assembly| trimgalore
        bbmap_align -->|reference,assembly| kraken
        bbmap_align -->|reference,assembly| clean_reads
    end

    subgraph reference_analyses [Reference based analysis]
        %%metro direction: BT
        bowtie2_align([Bowtie2])
        qualimap([QualiMap])
        monovar([MonoVar])
        doubletd([doubletD])
        preseq([Preseq])
        circlize([Coverage])

        bowtie2_align -->|reference| preseq
        bowtie2_align -->|reference| circlize
        bowtie2_align -->|reference| qualimap
        bowtie2_align -->|reference| monovar
        bowtie2_align -->|reference| doubletd
    end

    subgraph assembly_stage [Assembly based analysis]
        %%metro direction: LR
        bbnorm([BBNorm])
        spades([SPAdes])
        acdc([ACDC])
        checkm([CheckM])
        gtdbtk([GTDBTk])
        prokka([Prokka])
        phispy([PhiSpy])
        eggnog([eggNOG-mapper])
        kofamscan([KofamScan])
        genomad([geNomad])
        quast([QUAST])
        blobtools([BlobTools])

        bbnorm -->|assembly| spades
        spades -->|assembly| gtdbtk
        spades -->|assembly| genomad
        spades -->|assembly| checkm
        spades -->|assembly| quast
        spades -->|assembly| acdc
        spades -->|assembly| blobtools
        spades -->|assembly| prokka
        prokka -->|assembly| phispy
        prokka -->|assembly| eggnog
        prokka -->|assembly| kofamscan
    end

    clean_reads -->|reference| bowtie2_align
    clean_reads -->|assembly| bbnorm

