{% set name = "MGPGtools" %}
{% set version = "0.0.1-alpha.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gongyh/MGPGtools/archive/v{{ version }}.tar.gz
  sha256: e2eadc879b0d86c26158c2f6b2c8a455f015ff609623eb4e195afd43fb55ec1e

build:
  entry_points:
    - mgpgtools = main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.4
    - pip
  run:
    - python >=3.4
    - gfapy
    - biopython
    - pandas
    - toytree
    - prettytable
    - odgi
    - seqkit
    - clustalw

test:
  imports:
    - extern
  commands:
    - pip check
    - panTools --help
  requires:
    - pip

about:
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gongyh
