name: mgpg-tools
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::python=3
  - bioconda::odgi=0.8.4
  - bioconda::seqkit=2.5.1
  - bioconda::gfapy
  - bioconda::clustalw
  - bioconda::gffread
  - bioconda::aster
  - conda-forge::biopython
  - conda-forge::toytree
  - conda-forge::pandas
  - conda-forge::numpy
  - conda-forge::prettytable
  